networks:
  hicon:
    driver: bridge

services:
  nats:
    container_name: nats
    image: bitnami/nats
    restart: always
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    networks:
      - hicon
